/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springworkspace;

import lombok.Getter;

@Getter
class Person {

}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
